services:
  - type: web
    name: lemon-lime
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html